-- Create users table
create table users (
  id bigint generated by default as identity primary key,
  discord_id text unique not null,
  username text not null,
  registered_at timestamp with time zone default timezone('utc'::text, now()) not null,
  avatar_url text
);

-- Add index for faster lookups
create index idx_users_discord_id on users(discord_id);

-- Enable RLS
alter table users enable row level security;

-- Create policy for authenticated access
create policy "Enable read access for authenticated users" on users
  for select using (auth.role() = 'authenticated');