-- Create servers table
create table servers (
  id bigint generated by default as identity primary key,
  server_id text unique not null,
  name text not null,
  icon_url text,
  member_count integer not null,
  created_at timestamp with time zone not null,
  owner_id text not null
);

-- Add index for faster lookups
create index idx_servers_server_id on servers(server_id);

-- Enable RLS
alter table servers enable row level security;

-- Create policy for authenticated access
create policy "Enable read access for authenticated users" on servers
  for select using (auth.role() = 'authenticated');